export default {
  GET_LIST_REQUEST      : 'PRODUCT_KNOWLADGE_HISTORY_GET_LIST_REQUEST',
  GET_LIST_SUCCESS      : 'PRODUCT_KNOWLADGE_HISTORY_GET_LIST_SUCCESS',
  GET_LIST_FAILED       : 'PRODUCT_KNOWLADGE_HISTORY_GET_LIST_FAILED'
}