export default {
  GET_LIST_REQUEST      : 'TECHNOLOGY_CATEGORY_GET_LIST_REQUEST',
  GET_LIST_SUCCESS      : 'TECHNOLOGY_CATEGORY_GET_LIST_SUCCESS',
  GET_LIST_FAILED       : 'TECHNOLOGY_CATEGORY_GET_LIST_FAILED'
}