export default {
  GET_LIST_REQUEST      : 'TECHNICAL_KNOWLADGE_HISTORY_GET_LIST_REQUEST',
  GET_LIST_SUCCESS      : 'TECHNICAL_KNOWLADGE_HISTORY_GET_LIST_SUCCESS',
  GET_LIST_FAILED       : 'TECHNICAL_KNOWLADGE_HISTORY_GET_LIST_FAILED'
}